/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswortVergessenRouteImport } from './routes/passwort-vergessen'
import { Route as PasswortZuruecksetzenRouteImport } from './routes/passwort-zuruecksetzen'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as AuthenticatedAngeboteRouteImport } from './routes/_authenticated/angebote'
import { Route as AuthenticatedAufgabenRouteImport } from './routes/_authenticated/aufgaben'
import { Route as AuthenticatedAuftraegeRouteImport } from './routes/_authenticated/auftraege'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEinrichtungRouteImport } from './routes/_authenticated/einrichtung'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedInstallationRouteImport } from './routes/_authenticated/installation'
import { Route as AuthenticatedKiMitarbeiterRouteImport } from './routes/_authenticated/ki-mitarbeiter'
import { Route as AuthenticatedKonversationenRouteImport } from './routes/_authenticated/konversationen'
import { Route as AuthenticatedKundenRouteImport } from './routes/_authenticated/kunden'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedRechnungenRouteImport } from './routes/_authenticated/rechnungen'
import { Route as AuthenticatedTermineRouteImport } from './routes/_authenticated/termine'
import { Route as AuthenticatedUnternehmenRouteImport } from './routes/_authenticated/unternehmen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortVergessenRoute = PasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswortZuruecksetzenRoute = PasswortZuruecksetzenRouteImport.update({
  id: '/passwort-zuruecksetzen',
  path: '/passwort-zuruecksetzen',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAngeboteRoute = AuthenticatedAngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAufgabenRoute = AuthenticatedAufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuftraegeRoute = AuthenticatedAuftraegeRouteImport.update({
  id: '/auftraege',
  path: '/auftraege',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinrichtungRoute =
  AuthenticatedEinrichtungRouteImport.update({
    id: '/einrichtung',
    path: '/einrichtung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstallationRoute =
  AuthenticatedInstallationRouteImport.update({
    id: '/installation',
    path: '/installation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKiMitarbeiterRoute =
  AuthenticatedKiMitarbeiterRouteImport.update({
    id: '/ki-mitarbeiter',
    path: '/ki-mitarbeiter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKonversationenRoute =
  AuthenticatedKonversationenRouteImport.update({
    id: '/konversationen',
    path: '/konversationen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenRoute = AuthenticatedKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechnungenRoute = AuthenticatedRechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermineRoute = AuthenticatedTermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnternehmenRoute =
  AuthenticatedUnternehmenRouteImport.update({
    id: '/unternehmen',
    path: '/unternehmen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/registrieren': typeof RegistrierenRoute
  '/widget': typeof WidgetRoute
  '/angebote': typeof AuthenticatedAngeboteRoute
  '/aufgaben': typeof AuthenticatedAufgabenRoute
  '/auftraege': typeof AuthenticatedAuftraegeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einrichtung': typeof AuthenticatedEinrichtungRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/installation': typeof AuthenticatedInstallationRoute
  '/ki-mitarbeiter': typeof AuthenticatedKiMitarbeiterRoute
  '/konversationen': typeof AuthenticatedKonversationenRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/rechnungen': typeof AuthenticatedRechnungenRoute
  '/termine': typeof AuthenticatedTermineRoute
  '/unternehmen': typeof AuthenticatedUnternehmenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/registrieren': typeof RegistrierenRoute
  '/widget': typeof WidgetRoute
  '/angebote': typeof AuthenticatedAngeboteRoute
  '/aufgaben': typeof AuthenticatedAufgabenRoute
  '/auftraege': typeof AuthenticatedAuftraegeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einrichtung': typeof AuthenticatedEinrichtungRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/installation': typeof AuthenticatedInstallationRoute
  '/ki-mitarbeiter': typeof AuthenticatedKiMitarbeiterRoute
  '/konversationen': typeof AuthenticatedKonversationenRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/rechnungen': typeof AuthenticatedRechnungenRoute
  '/termine': typeof AuthenticatedTermineRoute
  '/unternehmen': typeof AuthenticatedUnternehmenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/passwort-vergessen': typeof PasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof PasswortZuruecksetzenRoute
  '/registrieren': typeof RegistrierenRoute
  '/widget': typeof WidgetRoute
  '/_authenticated/angebote': typeof AuthenticatedAngeboteRoute
  '/_authenticated/aufgaben': typeof AuthenticatedAufgabenRoute
  '/_authenticated/auftraege': typeof AuthenticatedAuftraegeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/einrichtung': typeof AuthenticatedEinrichtungRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/installation': typeof AuthenticatedInstallationRoute
  '/_authenticated/ki-mitarbeiter': typeof AuthenticatedKiMitarbeiterRoute
  '/_authenticated/konversationen': typeof AuthenticatedKonversationenRoute
  '/_authenticated/kunden': typeof AuthenticatedKundenRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/rechnungen': typeof AuthenticatedRechnungenRoute
  '/_authenticated/termine': typeof AuthenticatedTermineRoute
  '/_authenticated/unternehmen': typeof AuthenticatedUnternehmenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/widget'
    | '/angebote'
    | '/aufgaben'
    | '/auftraege'
    | '/dashboard'
    | '/einrichtung'
    | '/einstellungen'
    | '/installation'
    | '/ki-mitarbeiter'
    | '/konversationen'
    | '/kunden'
    | '/leads'
    | '/rechnungen'
    | '/termine'
    | '/unternehmen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/widget'
    | '/angebote'
    | '/aufgaben'
    | '/auftraege'
    | '/dashboard'
    | '/einrichtung'
    | '/einstellungen'
    | '/installation'
    | '/ki-mitarbeiter'
    | '/konversationen'
    | '/kunden'
    | '/leads'
    | '/rechnungen'
    | '/termine'
    | '/unternehmen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/registrieren'
    | '/widget'
    | '/_authenticated/angebote'
    | '/_authenticated/aufgaben'
    | '/_authenticated/auftraege'
    | '/_authenticated/dashboard'
    | '/_authenticated/einrichtung'
    | '/_authenticated/einstellungen'
    | '/_authenticated/installation'
    | '/_authenticated/ki-mitarbeiter'
    | '/_authenticated/konversationen'
    | '/_authenticated/kunden'
    | '/_authenticated/leads'
    | '/_authenticated/rechnungen'
    | '/_authenticated/termine'
    | '/_authenticated/unternehmen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  PasswortVergessenRoute: typeof PasswortVergessenRoute
  PasswortZuruecksetzenRoute: typeof PasswortZuruecksetzenRoute
  RegistrierenRoute: typeof RegistrierenRoute
  WidgetRoute: typeof WidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-vergessen': {
      id: '/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof PasswortVergessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwort-zuruecksetzen': {
      id: '/passwort-zuruecksetzen'
      path: '/passwort-zuruecksetzen'
      fullPath: '/passwort-zuruecksetzen'
      preLoaderRoute: typeof PasswortZuruecksetzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/angebote': {
      id: '/_authenticated/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AuthenticatedAngeboteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aufgaben': {
      id: '/_authenticated/aufgaben'
      path: '/aufgaben'
      fullPath: '/aufgaben'
      preLoaderRoute: typeof AuthenticatedAufgabenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auftraege': {
      id: '/_authenticated/auftraege'
      path: '/auftraege'
      fullPath: '/auftraege'
      preLoaderRoute: typeof AuthenticatedAuftraegeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einrichtung': {
      id: '/_authenticated/einrichtung'
      path: '/einrichtung'
      fullPath: '/einrichtung'
      preLoaderRoute: typeof AuthenticatedEinrichtungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installation': {
      id: '/_authenticated/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof AuthenticatedInstallationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ki-mitarbeiter': {
      id: '/_authenticated/ki-mitarbeiter'
      path: '/ki-mitarbeiter'
      fullPath: '/ki-mitarbeiter'
      preLoaderRoute: typeof AuthenticatedKiMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konversationen': {
      id: '/_authenticated/konversationen'
      path: '/konversationen'
      fullPath: '/konversationen'
      preLoaderRoute: typeof AuthenticatedKonversationenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden': {
      id: '/_authenticated/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof AuthenticatedKundenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rechnungen': {
      id: '/_authenticated/rechnungen'
      path: '/rechnungen'
      fullPath: '/rechnungen'
      preLoaderRoute: typeof AuthenticatedRechnungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/termine': {
      id: '/_authenticated/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof AuthenticatedTermineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unternehmen': {
      id: '/_authenticated/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof AuthenticatedUnternehmenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAngeboteRoute: typeof AuthenticatedAngeboteRoute
  AuthenticatedAufgabenRoute: typeof AuthenticatedAufgabenRoute
  AuthenticatedAuftraegeRoute: typeof AuthenticatedAuftraegeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEinrichtungRoute: typeof AuthenticatedEinrichtungRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedInstallationRoute: typeof AuthenticatedInstallationRoute
  AuthenticatedKiMitarbeiterRoute: typeof AuthenticatedKiMitarbeiterRoute
  AuthenticatedKonversationenRoute: typeof AuthenticatedKonversationenRoute
  AuthenticatedKundenRoute: typeof AuthenticatedKundenRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedRechnungenRoute: typeof AuthenticatedRechnungenRoute
  AuthenticatedTermineRoute: typeof AuthenticatedTermineRoute
  AuthenticatedUnternehmenRoute: typeof AuthenticatedUnternehmenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAngeboteRoute: AuthenticatedAngeboteRoute,
  AuthenticatedAufgabenRoute: AuthenticatedAufgabenRoute,
  AuthenticatedAuftraegeRoute: AuthenticatedAuftraegeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEinrichtungRoute: AuthenticatedEinrichtungRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedInstallationRoute: AuthenticatedInstallationRoute,
  AuthenticatedKiMitarbeiterRoute: AuthenticatedKiMitarbeiterRoute,
  AuthenticatedKonversationenRoute: AuthenticatedKonversationenRoute,
  AuthenticatedKundenRoute: AuthenticatedKundenRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedRechnungenRoute: AuthenticatedRechnungenRoute,
  AuthenticatedTermineRoute: AuthenticatedTermineRoute,
  AuthenticatedUnternehmenRoute: AuthenticatedUnternehmenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  PasswortVergessenRoute: PasswortVergessenRoute,
  PasswortZuruecksetzenRoute: PasswortZuruecksetzenRoute,
  RegistrierenRoute: RegistrierenRoute,
  WidgetRoute: WidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
