// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srufegisweghdswdsdxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydWZlZ2lzd2VnaGRzd2RzZHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NTY4OTAsImV4cCI6MjEwMjIzMjg5MH0.OE8VDnVcSo1lXi87pYo9KxUrvfwttc_5Bgpx4L7mnaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});